CREATE TABLE IF NOT EXISTS genre(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS artist(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS album(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	yearOf INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS track(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	timeOf INTEGER NOT NULL,
	album_ID INTEGER REFERENCES album(id)
);
CREATE TABLE IF NOT EXISTS collection(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	yearOf INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS genre_artist (
	genre_ID INTEGER REFERENCES genre(id),
	artist_ID INTEGER REFERENCES artist(id),
	CONSTRAINT ga_pk PRIMARY KEY(genre_ID, artist_ID)
);
CREATE TABLE IF NOT EXISTS artist_album (
	artist_ID INTEGER REFERENCES artist(id),
	album_ID INTEGER REFERENCES album(id),
	CONSTRAINT aa_pk PRIMARY KEY(artist_ID, album_ID)
);
CREATE TABLE IF NOT EXISTS collection_track (
	collection_ID INTEGER REFERENCES collection(id),
	track_ID INTEGER REFERENCES track(id),
	CONSTRAINT ct_pk PRIMARY KEY(collection_ID, track_ID)
);