CREATE TABLE IF NOT EXISTS part(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Employee (
	id SERIAL PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	part_ID INTEGER REFERENCES part(id),
	boss_ID INTEGER NOT NULL
);

ALTER TABLE Employee
ADD FOREIGN KEY (Boss_ID) REFERENCES Employee(id); 

